export const serviceIntervalsMtn = [
  {
    repeatMiles: 560,
    repeatDays: undefined,
    description: "Consider fork lower leg service",
    longDescription: "Depending on usage, consider a lower leg service for the fork. This involves cleaning the inside of the lower legs and replacing the bath oil of the fork.",
  },
  {
    repeatMiles: 1350,
    repeatDays: undefined,
    description: "Consider full shock and fork service",
    longDescription: "Full fork and shock service, including replacing seals, damper oil, and inspecting internal components. This interval may vary based on the type of riding and conditions.",
  },
  {
    repeatMiles: 125,
    repeatDays: undefined,
    description: "Check chain life and wear using a chain checker tool.",
    longDescription: "A well-maintained chain will shift better and extend the life of other drivetrain components.",
  },
  {
    repeatMiles: 750,
    repeatDays: undefined,
    description: "Check cassette and chainrings for wear.",
    longDescription: "Look for worn or missing teeth. Poor shifting and a chain that 'skips' are both indicators of a worn cassette.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 365,
    description: "Check derailleur cables and housing.",
    longDescription: "Worn cables can lead to imprecise shifting and decreased performance as well as shifting that takes too much physical force.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 274,
    description: "Check derailleurs for shifting performance.",
    longDescription: "Check for proper alignment and function. Inspect jockey wheels for wear and replace if needed",
  },
  {
    repeatMiles: undefined,
    repeatDays: 548,
    description: "Inspect bottom bracket.",
    longDescription: "Unusual noises or excessive play may indicate a need for replacement.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 548,
    description: "Inspect pedals.",
    longDescription: "Ensure smooth rotation and replace if there is excessive play or grinding noises.  Test that shoes can clip in with the right tension.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 183,
    description: "Check cable tension and indexing.",
    longDescription: "Ensure proper tension and smooth, precise, quick gear shifting.",
  },
  {
    repeatMiles: 200,
    repeatDays: undefined,
    description: "Inspect brake pads and rotors for wear.",
    longDescription: "Generally, pads should be replaced once they are down to one millimeter or less of material. Pads may need to be removed to adequately inspect. Rotors should be free from grooves and should be above the manufacturer recommended minimum thickness.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 183,
    description: "Inspect brake cables.",
    longDescription: "Look for wear, corrosion, or fraying. Replace if there are any signs of damage to ensure responsive braking.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 548,
    description: "Inspect bottom bracket.",
    longDescription: "Unusual noises or excessive play may indicate a need for replacement.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 730,
    description: "Replace brake fluid on hydraulic brakes.",
    longDescription: "Follow manufacturers recommendations.",
  },
  {
    repeatMiles: 200,
    repeatDays: undefined,
    description: "Inspect tires.",
    longDescription: "Look for wear, worn or torn off knobs, cuts in sidewalls, bulging, or other damage. For good traction and safe riding, always replace tires that are worn or damaged.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 90,
    description: "Check tire sealant, if used.",
    longDescription: "To avoid any suprises and potential long walks back to the car, make sure both tires have adequate sealant.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 548,
    description: "Inspect bottom bracket.",
    longDescription: "Unusual noises or excessive play may indicate a need for replacement.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 183,
    description: "Check all bolts and fasteners for appropriate tightness.",
    longDescription: "Look bolts can rapidly become big problems on the trail, and lead to unsafe riding. Use a torque when, especially with carbon frames and components.",
  },
  {
    repeatMiles: undefined,
    repeatDays: 365,
    description: "Inspect headset, bottom bracket, hubs, and frame linkage bearings.",
    longDescription: "Replace if there is noticable wear or they do not move freely.",
  },
];
